/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: hellitra (https://sketchfab.com/hellitra)
License: CC-BY-NC-ND-4.0 (http://creativecommons.org/licenses/by-nc-nd/4.0/)
Source: https://sketchfab.com/3d-models/boatrestaurant-c02032f8a7ee4c538e1f76e8f20a6c1b
Title: Boatrestaurant
*/

import React, { useRef, useEffect } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame, useThree } from "@react-three/fiber";
import islandScene from "../assets/3d/boatrestaurant.glb";
import { a } from "@react-spring/three";

const Island = (props) => {
  const { nodes, materials } = useGLTF(islandScene);
  const islandRef = useRef();
  return (
    <a.group ref={islandRef} {...props}>
      <group scale={0.01}>
        <mesh
          geometry={nodes.boat_restaurant_tutto_0.geometry}
          material={materials.tutto}
        />
        <mesh
          geometry={nodes.boat_restaurant_rete1_0.geometry}
          material={materials.rete1}
        />
      </group>
    </a.group>
  );
};

export default Island;
